#define _GNU_SOURCE
#include "ls.h"
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <stdlib.h>
#include <dirent.h>
#include "funcs.h"
#include <sys/types.h>
#include <pwd.h>
#include "main.h"
#include "colors.h"
#include <sys/stat.h>
#include <sys/wait.h>
#include "format.h"
#include <libgen.h>
#include <fcntl.h>
#include <grp.h>
#include <time.h>
#include <locale.h>
#include <langinfo.h>
#include <stdint.h>
#include "discover.h"
#include "term.h"